"""Excitatory/inhibitory population parameters for the neural-mass model.

The dynamical activity layer is a Wilson-Cowan-style mean-field model of two coupled
neural populations - excitatory (E) and inhibitory (I). :class:`EIParams` collects
the cited-range parameters that set their dynamics: the synaptic coupling weights
between and within the populations, the membrane time constants, the sigmoid
response gains and thresholds, and the external drive.

All quantities are SI where a unit applies: time constants and the drive timescale in
seconds, firing activities are dimensionless population activations in [0, 1] (the
Wilson-Cowan fraction-of-active-cells convention). The default :meth:`EIParams.central`
sits in a genuine gamma-band regime (~40 Hz); the motor-cortex presets place the E/I
loop in the beta band (high- and low-beta). The oscillation band is set primarily by
the inhibitory membrane time constant, per the gamma/beta mechanism literature (see the
individual preset docstrings for citations).
"""

from __future__ import annotations

from dataclasses import dataclass

from base_neural_model.base.bands import Band
from base_neural_model.base.provenance import Provenance


@dataclass(frozen=True)
class EIParams:
    """Wilson-Cowan E/I mean-field parameters (cited oscillatory regime).

    Coupling weights ``w_*`` are dimensionless synaptic gains; ``tau_*`` are membrane
    time constants (s); ``gain_*`` and ``theta_*`` set the slope and midpoint of the
    sigmoid response; ``drive_e``/``drive_i`` are the tonic external inputs.
    """

    w_ee: float          # E -> E recurrent excitation
    w_ei: float          # I -> E inhibition (enters E equation with a minus sign)
    w_ie: float          # E -> I excitation
    w_ii: float          # I -> I recurrent inhibition
    tau_e_s: float       # excitatory membrane time constant, seconds
    tau_i_s: float       # inhibitory membrane time constant, seconds
    gain_e: float        # excitatory sigmoid slope
    gain_i: float        # inhibitory sigmoid slope
    theta_e: float       # excitatory sigmoid threshold (midpoint)
    theta_i: float       # inhibitory sigmoid threshold (midpoint)
    drive_e: float       # tonic external drive to E
    drive_i: float       # tonic external drive to I
    provenance: Provenance
    # Anatomical columnar alignment Q_struct in [0, 1]: how aligned the population's
    # cell axes are in 3-D (the structural half of the directional channel). 0 =
    # isotropic (no directional signal regardless of synchrony, the default), 1 =
    # perfectly columnar (e.g. layer-5 pyramidal cells). The activity expresses this
    # through the temporal synchrony to produce the orientation coherence Q_eff.
    structural_alignment: float = 0.0

    def __post_init__(self) -> None:
        if self.tau_e_s <= 0.0 or self.tau_i_s <= 0.0:
            raise ValueError(
                f"time constants must be positive, got tau_e={self.tau_e_s!r}, "
                f"tau_i={self.tau_i_s!r}"
            )
        for name in ("w_ee", "w_ei", "w_ie", "w_ii"):
            if getattr(self, name) < 0.0:
                raise ValueError(f"coupling weight {name} must be >= 0")
        if self.gain_e <= 0.0 or self.gain_i <= 0.0:
            raise ValueError("sigmoid gains must be positive")
        if not 0.0 <= self.structural_alignment <= 1.0:
            raise ValueError(
                f"structural_alignment must lie in [0, 1], got "
                f"{self.structural_alignment!r}"
            )

    @classmethod
    def central(cls) -> EIParams:
        """Central-column E/I parameters in a genuine GAMMA-band regime (~40 Hz).

        Cortical gamma is generated by the fast recurrent E->I->E loop, with the
        oscillation period set chiefly by the *inhibitory* (GABA_A) decay time of
        roughly 5-10 ms (Buzsaki & Wang 2012, "Mechanisms of Gamma Oscillations",
        Annu Rev Neurosci 35:203-225; Wang 2010, Physiol Rev 90:1195-1268). A tau_i
        of ~5 ms with a matched fast tau_e places this E/I limit cycle near 40 Hz,
        squarely in the conventional gamma band (~30-80 Hz, dominant cortical peak
        ~30-45 Hz). This is the generic, isotropic cortical column (structural
        alignment 0).
        """
        return cls(
            w_ee=16.0,
            w_ei=12.0,
            w_ie=15.0,
            w_ii=3.0,
            tau_e_s=3.3e-3,  # fast excitation, matched to the fast inhibitory loop
            tau_i_s=5.2e-3,  # ~5 ms GABA_A decay -> gamma-band limit cycle (~40 Hz)
            gain_e=1.0,
            gain_i=1.0,
            theta_e=4.0,
            theta_i=3.7,
            drive_e=1.5,    # tonic drive sustaining a high-amplitude gamma cycle
            drive_i=0.0,
            provenance=Provenance(
                source=(
                    "Wilson & Cowan 1972 (E/I mean-field dynamics); gamma mechanism "
                    "and timescales: Buzsaki & Wang 2012 (Annu Rev Neurosci 35:203), "
                    "Wang 2010 (Physiol Rev 90:1195)"
                ),
                assumptions=(
                    "two coupled populations (E, I) as a mean field; activity is the "
                    "fraction of active cells in [0, 1], not a rate in Hz",
                    "sigmoid response S(x) = 1/(1 + exp(-gain (x - theta)))",
                    "cortical gamma is set by the fast GABA_A inhibitory loop: tau_i "
                    "~5 ms (Buzsaki & Wang 2012) -> limit cycle ~40 Hz, the dominant "
                    "cortical gamma band (30-45 Hz of the 30-80 Hz range)",
                    "tonic drive holds the loop in its oscillatory (limit-cycle) "
                    "regime; raising it raises mean activity and lowers frequency",
                ),
                band=Band.CONTENT_FAST,
            ),
        )

    @classmethod
    def motor_cortex(cls) -> EIParams:
        """Primary motor cortex (M1): a HIGH-BETA limit cycle (~20-25 Hz).

        M1's signature sensorimotor rhythm is beta (~13-30 Hz), not the gamma of the
        generic column (Baker 2007, Curr Opin Neurobiol 17:649-655; Kilavik et al.
        2013, Exp Neurol 245:15-26). The beta band splits into a high-beta (~20-30 Hz)
        and a low-beta (~13-20 Hz) component (Kilavik et al. 2013); this preset is the
        high-beta one (see :meth:`motor_cortex_low_beta` for the low-beta variant).

        The **fundamental** of the E/I limit cycle is placed at ~20 Hz (not a harmonic
        of a slower rhythm): the oscillation frequency is set by the geometric scale of
        the two time constants, while the ratio ``tau_i / tau_e ~ 2.8`` keeps the loop
        on a high-synchrony limit cycle (the delayed-inhibition Hopf mechanism needs
        ``tau_i > tau_e``; shrinking ``tau_i`` toward ``tau_e`` extinguishes the cycle).
        Fast-GABA inhibition (``tau_i ~ 7 ms``) with AMPA-fast excitation (``tau_e ~
        2.5 ms``) yields a ~20 Hz fundamental carrying ~76% of the oscillation power.
        The waveform is a non-sinusoidal **arch** with modest 2nd/3rd harmonics, which
        is the physiological shape of motor-cortical beta -- its sharpness tracks the
        synchrony of the underlying synaptic input (Cole et al. 2017, J Neurosci
        37:4830; Cole & Voytek 2017, Trends Cogn Sci 21:137).

        The defining structural difference is set here too: M1 layer-5 pyramidal cells
        (including the giant Betz cells) are large and strongly **columnar**, so the
        structural alignment ``Q_struct`` is high - which, expressed through the
        movement-locked synchrony, drives the directional channel that a generic
        isotropic patch lacks.
        """
        return cls(
            w_ee=16.0,
            w_ei=12.0,
            w_ie=15.0,
            w_ii=3.0,
            tau_e_s=2.5e-3,   # AMPA-fast excitation; sets the fast E/I loop scale
            tau_i_s=7.0e-3,   # fast-GABA inhibition; tau_i/tau_e ~ 2.8 -> ~20 Hz fundamental
            gain_e=1.0,
            gain_i=1.0,
            theta_e=4.0,
            theta_i=3.7,
            drive_e=1.3,
            drive_i=0.0,
            structural_alignment=0.9,  # layer-5 pyramidal columns: strongly aligned
            provenance=Provenance(
                source=(
                    "Wilson & Cowan E/I mean field tuned to the M1 high-beta rhythm; "
                    "beta sensorimotor rhythm and its high/low split (Baker 2007, Curr "
                    "Opin Neurobiol 17:649; Kilavik et al. 2013, Exp Neurol 245:15); "
                    "non-sinusoidal arch waveform of motor beta (Cole et al. 2017, J "
                    "Neurosci 37:4830); layer-5 (Betz) columnar alignment (Murphy 2016)"
                ),
                assumptions=(
                    "M1 sensorimotor rhythm is beta (~13-30 Hz); the E/I FUNDAMENTAL "
                    "is placed at ~20 Hz (high-beta) by fast-GABA/AMPA time constants "
                    "(tau_i ~ 7 ms, tau_e ~ 2.5 ms), NOT as a harmonic of a slower "
                    "rhythm; the ratio tau_i/tau_e ~ 2.8 sustains a high-synchrony cycle",
                    "the beta waveform is a non-sinusoidal arch (~76% power in the "
                    "fundamental, modest harmonics); its sharpness reflects input "
                    "synchrony (Cole et al. 2017) -- a feature, not an artifact",
                    "layer-5 pyramidal / Betz cells are large and strongly columnar "
                    "-> high structural alignment Q_struct ~ 0.9 (vs ~0 for an "
                    "isotropic patch); the directional channel is material in M1",
                    "structural alignment is expressed as orientation coherence "
                    "through the temporal synchrony (Q_eff = Q_struct * s)",
                ),
                band=Band.CONTENT_FAST,
            ),
        )

    @classmethod
    def motor_cortex_low_beta(cls) -> EIParams:
        """Primary motor cortex (M1): a LOW-BETA limit cycle (~13-17 Hz).

        The low-beta companion to :meth:`motor_cortex`. Sensorimotor beta is not a
        single peak but comprises distinct low-beta (~13-20 Hz) and high-beta
        (~20-30 Hz) components with different movement-related behaviour (Kilavik et
        al. 2013, Exp Neurol 245:15-26). As in the high-beta preset the E/I
        **fundamental** is placed in-band -- here at ~15 Hz -- by scaling both time
        constants up together (``tau_i ~ 9 ms``, ``tau_e ~ 3.5 ms``) while holding the
        ``tau_i / tau_e ~ 2.6`` ratio that sustains the high-synchrony limit cycle; a
        slower loop than the high-beta preset lowers the fundamental, not a harmonic.
        The same non-sinusoidal arch waveform applies (Cole et al. 2017). Columnar
        structure and the M1 mechanics are identical to :meth:`motor_cortex`; only the
        rhythm differs.
        """
        return cls(
            w_ee=16.0,
            w_ei=12.0,
            w_ie=15.0,
            w_ii=3.0,
            tau_e_s=3.5e-3,  # slower than high-beta -> lower fundamental, same ratio
            tau_i_s=9.0e-3,  # tau_i/tau_e ~ 2.6 -> ~15 Hz low-beta fundamental
            gain_e=1.0,
            gain_i=1.0,
            theta_e=4.0,
            theta_i=3.7,
            drive_e=1.3,     # same drive as high-beta; the slower loop sets the lower freq
            drive_i=0.0,
            structural_alignment=0.9,  # same M1 layer-5 columnar alignment
            provenance=Provenance(
                source=(
                    "Wilson & Cowan E/I mean field tuned to the M1 low-beta rhythm; "
                    "low/high beta components of the sensorimotor rhythm (Kilavik et "
                    "al. 2013, Exp Neurol 245:15; Baker 2007, Curr Opin Neurobiol "
                    "17:649); layer-5 columnar alignment (Murphy et al. 2016)"
                ),
                assumptions=(
                    "sensorimotor beta has distinct low-beta (~13-20 Hz) and high-beta "
                    "(~20-30 Hz) components (Kilavik et al. 2013); the E/I FUNDAMENTAL "
                    "is placed at ~15 Hz (low-beta) by a slower loop (tau_i ~ 9 ms, "
                    "tau_e ~ 3.5 ms) than high-beta, at the same ratio, NOT as a harmonic",
                    "layer-5 pyramidal / Betz columnar alignment Q_struct ~ 0.9, as in "
                    "the high-beta preset; the directional channel is material",
                    "structural alignment is expressed as orientation coherence "
                    "through the temporal synchrony (Q_eff = Q_struct * s)",
                ),
                band=Band.CONTENT_FAST,
            ),
        )
