"""Temporal bands and the envelope-vs-content guard (Design Invariant 3).

Every displacement quantity carries a band label. The model must never let a
slow-envelope (rhythm/timing) figure stand in for a fast-content figure: that
category error silently swaps "when speech happens" for "what the speech is" and
corrupts the verdict. The guard here makes the error a raised exception rather
than a comment - it is a typed constraint.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


class Band(Enum):
    """Temporal band of a displacement quantity.

    Guards against the envelope-vs-content category error (Invariant 3).
    """

    CONTENT_FAST = "content_fast"    # the band Lucen must detect
    ENVELOPE_SLOW = "envelope_slow"  # rhythm; timing only, NOT content
    BROADBAND = "broadband"          # unseparated; disallowed past Module 1


class BandError(ValueError):
    """Raised when a displacement quantity is in the wrong temporal band for the
    operation requested - e.g. feeding an envelope figure into the population
    summation that must operate on the content band."""


def require_content_fast(band: Band, *, context: str = "operation") -> None:
    """Assert that ``band is Band.CONTENT_FAST``, else raise ``BandError``.

    Call this at every entry point that must operate on the content band (the
    single-neuron displacement, the population summation). ``context`` names the
    caller so the failure message points at the offending boundary.
    """
    if band is not Band.CONTENT_FAST:
        raise BandError(
            f"{context} requires a {Band.CONTENT_FAST.value!r} displacement, "
            f"but received {band.value!r}. The fast/content band is the target, "
            f"never the slow envelope (Invariant 3)."
        )


@dataclass(frozen=True)
class RhythmBand:
    """The admissible content-frequency window ``[f_lo_hz, f_hi_hz]`` of a rhythm.

    A rhythm's content band is not a single global constant: a beta motor rhythm
    carries its information in ~13-30 Hz, but a gamma column carries it in ~30-80 Hz.
    Pinning one hardcoded box (the beta one) to every preset silently *amputates*
    gamma -- a 40 Hz fundamental falls above a 30 Hz ceiling and cannot be recovered.

    This makes the window an explicit, toggleable per-rhythm object with two edges:

    * ``f_lo_hz`` -- the envelope/content lower edge. Below it is slow sub-rhythm
      modulation (the movement envelope / mu-band timing), which is *not* a content
      carrier (Invariant 3). Used by the mechanics-side content/envelope split.
    * ``f_hi_hz`` -- the admissible upper edge. Above it the rhythm's harmonics carry
      negligible power. Used by the forward-layer band optimizer to bound its search.

    The named presets (:attr:`GAMMA`, :attr:`HIGH_BETA`, :attr:`LOW_BETA`) let each
    rhythm supply its own box so the beta bounds never clamp a gamma (or high-/low-beta)
    content-band recovery.
    """

    f_lo_hz: float
    f_hi_hz: float

    def __post_init__(self) -> None:
        if not 0.0 < self.f_lo_hz < self.f_hi_hz:
            raise ValueError(
                f"rhythm band must satisfy 0 < f_lo < f_hi, got "
                f"[{self.f_lo_hz!r}, {self.f_hi_hz!r}]"
            )

    def contains(self, f_hz: float) -> bool:
        """True iff ``f_hz`` lies within the admissible window (inclusive)."""
        return self.f_lo_hz <= f_hz <= self.f_hi_hz


# Sensorimotor beta (~13-30 Hz): the M1 motor rhythm. Split into low- and high-beta
# components (Kilavik et al. 2013, Exp Neurol 245:15); they share the same admissible
# box, differing only in where their fundamental sits inside it. This is the shipped
# default so existing (motor) callers are unchanged.
BETA_BAND: RhythmBand = RhythmBand(f_lo_hz=13.0, f_hi_hz=30.0)
HIGH_BETA_BAND: RhythmBand = BETA_BAND
LOW_BETA_BAND: RhythmBand = BETA_BAND

# Cortical gamma (~30-80 Hz): the generic column's rhythm, generated by the fast
# recurrent E->I->E loop (Buzsaki & Wang 2012, Annu Rev Neurosci 35:203). Its ~40 Hz
# fundamental sits ABOVE the beta ceiling, so it needs its own admissible box.
GAMMA_BAND: RhythmBand = RhythmBand(f_lo_hz=30.0, f_hi_hz=80.0)
